routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('peoples', 'PeopleController');

app/Models/People.php
<?php

namespace App\Models;

use App\Models\Film;
use App\Models\HomeWorld;
use App\Models\Gender;
use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class People extends Model implements Transformable
{
    use TransformableTrait;

    protected $table = 'people';

    protected $fillable = [
        'name','height','mass','hair_color','birth_year','gender_id','homeworld_id', 'url'
    ];

    public function films(){
        return $this->belongsToMany(Film::class, 'film_people');
    }

    public function homeworld(){
        return $this->belongsTo(HomeWorld::class);
    }

    public function gender(){
        return $this->belongsTo(Gender::class);
    }
}

app/Http/Controllers/PeopleController.php
<?php

namespace App\Http\Controllers;

use Prettus\Validator\Contracts\ValidatorInterface;
use Prettus\Validator\Exceptions\ValidatorException;
use App\Http\Requests\PeopleCreateRequest;
use App\Http\Requests\PeopleUpdateRequest;
use App\Repositories\PeopleRepository;
use App\Repositories\FilmRepository;
use App\Repositories\HomeWorldRepository;
use App\Repositories\GenderRepository;
use App\Validators\PeopleValidator;

/**
 * Class PeopleController.
 *
 * @package namespace App\Http\Controllers;
 */
class PeopleController extends Controller
{
    /**
     * @var PeopleRepository
     */
    protected $repository;

    /**
     * @var PeopleValidator
     */
    protected $validator;

    /**
     * PeopleController constructor.
     *
     * @param PeopleRepository $repository
     * @param PeopleValidator $validator
     */
    public function __construct(PeopleRepository $repository, PeopleValidator $validator)
    {
        $this->repository = $repository;
        $this->validator = $validator;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->repository->pushCriteria(app('Prettus\Repository\Criteria\RequestCriteria'));
        $peoples = $this->repository->with(['films', 'homeworld'])->paginate(10);

        return view('people.index', compact('peoples'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param GenderRepository $genderRepository
     * @param HomeWorldRepository $homeWorldRepository
     * @param FilmRepository $filmRepository
     * @return Response
     */
    public function create(GenderRepository $genderRepository, HomeWorldRepository $homeWorldRepository,
                           FilmRepository $filmRepository)
    {
        $fields = [
            'name', 'height', 'mass', 'hair_color', 'birth_year', 'url'
        ];

        $genders = $genderRepository->all();
        $homeWorlds = $homeWorldRepository->all();
        $films = $filmRepository->all();

        return view('people.create', compact('genders', 'homeWorlds', 'films', 'fields'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param PeopleCreateRequest $request
     *
     * @param FilmRepository $filmRepository
     * @return \Illuminate\Http\Response
     *
     */
    public function store(PeopleCreateRequest $request, FilmRepository $filmRepository)
    {
        try {

            $this->validator->with($request->all())->passesOrFail(ValidatorInterface::RULE_CREATE);

            $people = $this->repository->create($request->all());

            $films = $filmRepository->findWhereIn('id', $request->input('films_id'));
            $people->films()->sync($films);

            $response = [
                'message' => 'People created.'
            ];

            return redirect()->back()->with('message', $response['message']);
        } catch (ValidatorException $e) {
            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     *
     * @param HomeWorldRepository $homeWorldRepository
     * @return \Illuminate\Http\Response
     */
    public function show($id, HomeWorldRepository $homeWorldRepository)
    {
        $homeWorlds = $homeWorldRepository->with(['peoples'])->paginate(10);

        return view('people.show', compact('homeWorlds'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     *
     * @param GenderRepository $genderRepository
     * @param HomeWorldRepository $homeWorldRepository
     * @param FilmRepository $filmRepository
     * @return \Illuminate\Http\Response
     */
    public function edit($id, GenderRepository $genderRepository, HomeWorldRepository $homeWorldRepository,
                         FilmRepository $filmRepository)
    {
        $fields = [
            'id', 'name', 'height', 'mass', 'hair_color', 'birth_year', 'url'
        ];

        $people = $this->repository->find($id);
        $genders = $genderRepository->all();
        $homeWorlds = $homeWorldRepository->all();
        $films = $filmRepository->all();

        return view('people.edit', compact('people', 'homeWorlds', 'genders', 'films', 'fields'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param PeopleUpdateRequest $request
     * @param string $id
     *
     * @return Response
     *
     * @throws \Prettus\Validator\Exceptions\ValidatorException
     */
    public function update(PeopleUpdateRequest $request, $id)
    {
        try {

            $this->validator->with($request->all())->passesOrFail(ValidatorInterface::RULE_UPDATE);

            $this->repository->update($request->all(), $id);

            $response = [
                'message' => 'People updated.'
            ];

            return redirect()->back()->with('message', $response['message']);
        } catch (ValidatorException $e) {
            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->repository->delete($id);

        return redirect()->back()->with('message', 'People deleted.');
    }
}

resources/views/people/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row col-12">
        <form id="form" class="col-lg-5 mx-auto" action="{{ route('peoples.store') }}" method="POST">
            @csrf
            @method('POST')

            @if (isset($errors) ? $errors->any() : false)
                <div class="col-12">
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            @endif
            @if (\Session::has('message'))
                <div class="col-12">
                    <div class="alert alert-success">
                        <ul>
                            <li>{{ \Session::get('message')}}</li>
                        </ul>
                    </div>
                </div>
            @endif
            @foreach($fields as $field)
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">{{$field}}:</label>
                    <div class="col-sm-9">
                        <input type="{{ $field === 'birth_year' ? 'date' : 'text'}}"
                               id="{{$field}}"
                               name="{{$field}}"
                               class="form-control"
                               placeholder="Enter {{$field}}..."
                               required>
                    </div>
                </div>
            @endforeach
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">gender:</label>
                <div class="col-sm-9">
                    <select id="gender_id" name="gender_id" class="form-control" required>
                        <option value="" disabled selected>Choose your option</option>
                        {{$i = 1}}
                        @foreach($genders as $gender)
                            <option value="{{$i++}}">{{$gender['name']}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">home world:</label>
                <div class="col-sm-9">
                    <select id="homeworld_id" name="homeworld_id" class="form-control" required>
                        <option value="" disabled selected>Choose your option</option>
                        {{$i = 1}}
                        @foreach($homeWorlds as $homeWorld)
                            <option value="{{$i++}}">{{$homeWorld['name']}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">films:</label>
                <div class="col-sm-9">
                    <select id="films_id" name="films_id[]" class="form-control" multiple="multiple" required>
                        {{$i = 1}}
                        @foreach($films as $film)
                            <option value="{{$i++}}">{{$film['title']}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <a class="btn btn-primary btn-lg"
                   id="sendMessage"
                   href="{{ route('peoples.store') }}">Create</a>
            </div>
        </form>
    </div>


    <script>
        $(document).ready(() => {
            const inputs = [
                $('#height'),
                $('#mass'),
                $('#gender_id'),
                $('#homeworld_id')];

            const url = $('#url').val();
            const errors = [];

            $('#sendMessage').on('click', (e) => {
                e.preventDefault();

                let success = true;

                const selected = $('#films_id option:checked');
                const values = Array.from(selected).map(
                    el => Number.isInteger(+el.value) ? +el.value :
                        success ? errors.push('films_id') :
                            errors.length > 0 ? success = false : ''
                );

                inputs.forEach(function (item) {
                    Number.isInteger(+item.val()) ? '' : success = false;
                    Number.isInteger(+item.val()) ? '' : errors.push(item.attr('id'));
                });

                const regex = /https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-z]{2,63}\b([-a-zA-Z0-9@:%_\+.~#?&=]*)/i;
                regex.test(url)

                if (success) {
                    $('#form').submit();
                } else {
                    errors.forEach(function (item) {
                        $(`#${item}`).addClass('alert alert-danger')
                    });
                }
            })
        });
    </script>
@endsection

resources/views/people/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row col-12">
        <form id="form" class="col-lg-5 mx-auto" action="{{ route('peoples.update', $people) }}" method="POST">
            @csrf
            @method('PATCH')

            @if (isset($errors) ? $errors->any() : false)
                <div class="col-12">
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            @endif
            @if (\Session::has('message'))
                <div class="col-12">
                    <div class="alert alert-success">
                        <ul>
                            <li>{{ \Session::get('message')}}</li>
                        </ul>
                    </div>
                </div>
            @endif
            @foreach($fields as $field)
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">{{$field}}:</label>
                    <div class="col-sm-9">
                        <input type="text"
                               id="{{$field}}"
                               name="{{$field}}"
                               class="form-control"
                               placeholder="Enter {{$field}}..."
                               value="{{$people->$field}}"
                               required>
                    </div>
                </div>
            @endforeach
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">gender:</label>
                <div class="col-sm-9">
                    <select id="gender_id" name="gender_id" class="form-control">
                        <option value="" disabled>Choose your option</option>
                        {{$i = 1}}
                        @foreach($genders as $gender)
                            <option
                                {{ $gender['name'] === $people->gender_id['name'] ? 'selected="selected"' : '' }}
                                value="{{$i++}}">{{$gender['name']}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">home world:</label>
                <div class="col-sm-9">
                    <select id="homeworld_id" name="homeworld_id" class="form-control">
                        <option value="" disabled>Choose your option</option>
                        {{$i = 1}}
                        @foreach($homeWorlds as $homeWorld)
                            <option
                                {{ $homeWorld['name'] === $people->homeworld['name'] ? 'selected="selected"' : '' }}
                                value="{{$i++}}">{{$homeWorld['name']}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">films:</label>
                <div class="col-sm-9">
                    <select id="films_id" name="films_id[]" class="form-control" multiple="multiple">
                        {{$i = 1}}
                        @foreach($films as $film)
                            <option
                                @foreach($people->films as $peopleFilm)
                                {{ $film['title'] === $peopleFilm['title'] ? 'selected="selected"' : '' }}
                                @endforeach
                                value="{{$i++}}">{{$film['title']}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <a class="btn btn-primary btn-lg"
                   id="sendMessage"
                   href="{{ route('peoples.update', $people) }}">Edit</a>
            </div>
        </form>
    </div>


    <script>
        $(document).ready(() => {
            const inputs = [
                $('#height'),
                $('#mass'),
                $('#gender_id'),
                $('#homeworld_id')];

            const url = $('#url').val();
            const errors = [];

            $('#sendMessage').on('click', (e) => {
                e.preventDefault();

                let success = true;

                const selected = $('#films_id option:checked');
                const values = Array.from(selected).map(
                    el => Number.isInteger(+el.value) ? +el.value :
                        success ? errors.push('films_id') :
                            errors.length > 0 ? success = false : ''
                );

                inputs.forEach(function (item) {
                    Number.isInteger(+item.val()) ? '' : success = false;
                    Number.isInteger(+item.val()) ? '' : errors.push(item.attr('id'));
                });

                const regex = /https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-z]{2,63}\b([-a-zA-Z0-9@:%_\+.~#?&=]*)/i;
                regex.test(url)

                if (success) {
                    $('#form').submit();
                } else {
                    errors.forEach(function (item) {
                        $(`#${item}`).addClass('alert alert-danger')
                    });
                }
            })
        });
    </script>
@endsection

resources/views/people/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-12">
            <table class="table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Height</th>
                    <th>Mass</th>
                    <th>Hair Color</th>
                    <th>Birth Year</th>
                    <th>Gender</th>
                    <th>HomeWorld</th>
                    <th>Films</th>
                    <th>Url</th>
                    <th>Created_at</th>
                    <th>Updated_at</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                @if ($peoples->total() === 0)
                    <tr>
                        <td colspan="3" class="text-center">Empty...</td>
                    </tr>
                @else
                    @foreach($peoples->items() as $item)
                        <tr>
                            <th>{{ $item->id }}</th>
                            <th>{{ $item->name }}</th>
                            <th>{{ $item->height }}</th>
                            <th>{{ $item->mass }}</th>
                            <th>{{ $item->hair_color }}</th>
                            <th>{{ $item->birth_year }}</th>
                            <th>{{ $item->gender['name'] }}</th>
                            <th>
                                <a href="{{ $item->homeworld['url'] }}">{{ $item->homeworld['name'] }}</a>
                            </th>
                            <th>
                                <div class="dropdown show">
                                    <a class="btn btn-primary dropdown-toggle" href="#" role="button"
                                       id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
                                       aria-expanded="false">Films</a>

                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                        @foreach($item->films as $film)
                                            <a class="dropdown-item" href="{{ ($film['url']) }}">{{$film['title']}}</a>
                                        @endforeach
                                    </div>
                                </div>
                            </th>
                            <th>
                                <a href="{{ $item->url }}">{{ $item->url }}</a>
                            </th>
                            <th>{{ $item->created_at }}</th>
                            <th>{{ $item->updated_at }}</th>
                            <td class="text-right">
                                <div class="btn-group text-left">
                                    <a href="{{ route('peoples.edit', $item->id) }}"
                                       class="btn btn-primary btn-sm" data-toggle="tooltip"
                                       data-placement="top" title="Редактировать"><i class="fas fa-edit"></i></a>
                                    <form id="delete-form-{{ $item->id }}" action="{{ route('peoples.destroy', $item->id) }}" method="POST" style="display: none;">
                                        @csrf
                                        @method('delete')
                                    </form>

                                    <a href="#" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#questionModal-{{ $item->id }}"><i class="fas fa-trash"></i></a>

                                    <div class="modal fade" id="questionModal-{{ $item->id }}" tabindex="-1" role="dialog" aria-hidden="true">
                                        <div class="modal-dialog modal-xl" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title">Вы уверены что хотите удалить?</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">×</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body text-right">
                                                    <a class="btn btn-sm btn-danger" href="{{ route('peoples.destroy', $item->id) }}"
                                                       onclick="event.preventDefault();
                                                           document.getElementById('delete-form-{{ $item->id }}').submit();"><i class="fas fa-trash"></i></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                @endif
                </tbody>
            </table>
        </div>
        <div class="col-12">
            {{$peoples->links()}}
        </div>
    </div>
@endsection

resources/views/people/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-12">
            <table class="table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Planet Name</th>
                    <th class="row" style="justify-content: space-between; margin: 0">
                        <span>Peoples</span>
                        <span>Films</span>
                    </th>
                </tr>
                </thead>
                <tbody>
                @if ($homeWorlds->total() === 0)
                    <tr>
                        <td colspan="3" class="text-center">Empty...</td>
                    </tr>
                @else
                    @foreach($homeWorlds->items() as $item)
                        <tr>
                            <th>{{ $item->id }}</th>
                            <th>
                                <a href="{{ $item->url }}">{{ $item->name }}</a>
                            </th>
                            <th>
                                <ul style="padding-left: 15px;">
                                    @foreach($item->peoples as $people)
                                        <li class="row" style="justify-content: space-between">
                                            <a href="{{ $people->url }}">{{ $people->name }}</a>

                                            <div class="dropdown show">
                                                <a class="dropdown-toggle text-right"
                                                   href="#" role="button"
                                                   id="dropdownMenuLink"
                                                   data-toggle="dropdown"
                                                   aria-haspopup="true"
                                                   aria-expanded="false">Films</a>

                                                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                                    @foreach($people->films as $film)
                                                        <a class="dropdown-item"
                                                           href="{{ ($film['url']) }}">{{$film['title']}}</a>
                                                    @endforeach
                                                </div>
                                            </div>
                                        </li>
                                    @endforeach
                                </ul>
                            </th>
                        </tr>
                    @endforeach
                @endif
                </tbody>
            </table>
        </div>
        <div class="col-12">
            {{$homeWorlds->links()}}
        </div>
    </div>
@endsection